/**
 * Course glossary.
 *
 * Each term deep-links to the lesson that introduces it, so the glossary
 * doubles as an index. `chapter`/`lesson` are slugs from `content.ts`; the
 * optional `section` is a heading anchor within that lesson.
 */

export type GlossaryTerm = {
  term: string;
  definition: string;
  chapter?: string;
  lesson?: string;
  section?: string;
};

const term = (
  name: string,
  definition: string,
  chapter?: string,
  lesson?: string,
  section?: string,
): GlossaryTerm => ({ term: name, definition, chapter, lesson, section });

export const glossary: GlossaryTerm[] = [
  // Chapter 1-2 — foundations and probability
  term(
    "Descriptive statistics",
    "Summaries of data you have completely observed — a mean, a median, a histogram. They make no claim beyond the rows in front of you.",
    "groundwork",
    "why-quantitative-thinking",
    "stats-vs-quant",
  ),
  term(
    "Inferential statistics",
    "Using a sample to make claims about a population you did not fully observe. This is where uncertainty, and most of the interesting machinery, enters.",
    "groundwork",
    "why-quantitative-thinking",
    "stats-vs-quant",
  ),
  term(
    "Theoretical probability",
    "A probability derived from an assumed model of equally likely outcomes, such as 1/6 for a fair die, without collecting data.",
    "probability",
    "basic-probability",
    "three-types",
  ),
  term(
    "Empirical probability",
    "A probability estimated from observed frequencies: the number of times an event occurred divided by the number of observations.",
    "probability",
    "basic-probability",
    "three-types",
  ),
  term(
    "Odds",
    "The ratio of favourable to unfavourable outcomes, P/(1−P). Logistic regression models the logarithm of this quantity.",
    "probability",
    "basic-probability",
    "odds",
  ),
  term(
    "Gambler's fallacy",
    "The belief that independent events 'even out' in the short run — that tails is due after a run of heads. The law of large numbers says nothing about the next trial.",
    "probability",
    "basic-probability",
    "the-denominator",
  ),
  term(
    "Multiplication rule",
    "P(A and B) = P(A)P(B|A). For independent events this simplifies to P(A)P(B), and assuming independence when it does not hold understates joint risk.",
    "probability",
    "counting-rules",
    "multiplication-rule",
  ),
  term(
    "Mutually exclusive",
    "Two events that cannot both occur. Their joint probability is zero, so the simple addition rule applies.",
    "probability",
    "counting-rules",
    "addition-rule",
  ),
  term(
    "Permutation",
    "An ordered arrangement of k items chosen from n. P(n,k) = n!/(n−k)!.",
    "probability",
    "permutations-and-combinations",
    "permutations",
  ),
  term(
    "Combination",
    "An unordered selection of k items from n. C(n,k) = n!/(k!(n−k)!) — the permutation count divided by k!.",
    "probability",
    "permutations-and-combinations",
    "combinations",
  ),
  term(
    "Random variable",
    "A rule assigning a number to each outcome of an experiment. Discrete variables take countably many values; continuous ones take any value in an interval.",
    "probability",
    "random-variables",
    "discrete-vs-continuous",
  ),
  term(
    "Probability mass function (PMF)",
    "For a discrete random variable, the probability of each individual value. The values sum to 1.",
    "probability",
    "random-variables",
    "pmf",
  ),
  term(
    "Probability density function (PDF)",
    "For a continuous random variable, probability per unit of x. A density is not a probability and may exceed 1; probability comes from the area under it.",
    "probability",
    "random-variables",
    "pdf",
  ),
  term(
    "Cumulative distribution function (CDF)",
    "F(x) = P(X ≤ x). Every interval question reduces to a subtraction of two CDF values, which is why it is the workhorse of applied probability.",
    "probability",
    "random-variables",
    "cdf",
  ),
  term(
    "Expected value",
    "The probability-weighted average of a random variable's values — its long-run mean over many repetitions.",
    "probability",
    "random-variables",
    "pmf",
  ),

  // Chapter 3 — distributions
  term(
    "Normal distribution",
    "The symmetric bell curve, specified by a mean and a standard deviation. Arises wherever many small independent effects accumulate additively.",
    "distributions",
    "normal-distribution",
    "shape",
  ),
  term(
    "Central limit theorem",
    "Sums and averages of many independent contributions tend toward a normal distribution, whatever the shape of the individual contributions.",
    "distributions",
    "normal-distribution",
    "shape",
  ),
  term(
    "z-score",
    "A value expressed as its distance from the mean in standard deviations: (x − μ)/σ. Makes quantities on different scales directly comparable.",
    "distributions",
    "normal-distribution",
    "z-scores",
  ),
  term(
    "Empirical rule",
    "For a normal distribution, roughly 68%, 95% and 99.7% of values lie within one, two and three standard deviations of the mean.",
    "distributions",
    "normal-distribution",
    "empirical-rule",
  ),
  term(
    "Binomial distribution",
    "The number of successes in a fixed number of independent trials with constant success probability. Requires all four of those conditions.",
    "distributions",
    "binomial-distribution",
    "the-setup",
  ),
  term(
    "Poisson distribution",
    "Counts of rare, independent events in a fixed window, at a constant average rate. Its mean and variance are equal — the key diagnostic.",
    "distributions",
    "uniform-and-poisson",
    "poisson",
  ),
  term(
    "Overdispersion",
    "Count data whose variance exceeds its mean, usually because events cluster. A plain Poisson model then understates the tail.",
    "distributions",
    "uniform-and-poisson",
    "when-poisson-applies",
  ),
  term(
    "Index of dispersion",
    "Variance divided by mean. Near 1 is consistent with Poisson; well above 1 indicates clustering.",
    "distributions",
    "uniform-and-poisson",
    "when-poisson-applies",
  ),
  term(
    "Complement rule",
    "P(A) = 1 − P(not A). The reason 'at least one' questions are almost always easier computed from the other side.",
    "distributions",
    "probability-rules",
    "complement-rule",
  ),
  term(
    "Conditional probability",
    "P(A | B) = P(A ∩ B)/P(B) — the probability of A once the sample space has been narrowed to outcomes where B occurred.",
    "distributions",
    "conditional-probability",
    "the-idea",
  ),
  term(
    "Independence",
    "Two events are independent exactly when P(A|B) = P(A) — conditioning on one tells you nothing about the other.",
    "distributions",
    "conditional-probability",
    "independence",
  ),
  term(
    "Bayes' theorem",
    "The rule for updating a prior belief with evidence: posterior ∝ likelihood × prior. Explains why a 99%-accurate test can still be wrong most of the time it fires.",
    "distributions",
    "conditional-probability",
    "bayes",
  ),
  term(
    "Base rate",
    "The unconditional prevalence of an outcome. Ignoring it — the base-rate fallacy — is the most consequential error in applied probability.",
    "distributions",
    "conditional-probability",
    "natural-frequencies",
  ),
  term(
    "Prosecutor's fallacy",
    "Confusing P(A|B) with P(B|A). The probability of coughing given a cold is not the probability of a cold given coughing.",
    "distributions",
    "conditional-probability",
    "the-idea",
  ),

  // Chapter 4-5 — regression
  term(
    "Ordinary least squares (OLS)",
    "Fitting a line by minimising the sum of squared vertical distances. Has a closed-form solution but is sensitive to outliers.",
    "linear-regression",
    "the-linear-model",
    "least-squares",
  ),
  term(
    "R-squared",
    "The proportion of the response's variance the model accounts for. Never decreases when predictors are added, which is why adjusted R² exists.",
    "linear-regression",
    "the-linear-model",
    "r-squared",
  ),
  term(
    "Adjusted R-squared",
    "R² penalised for the number of predictors. The figure to quote for multiple regression, and the one that goes negative when predictors are noise.",
    "linear-regression",
    "the-linear-model",
    "r-squared",
  ),
  term(
    "Residual",
    "The difference between an observed value and the model's fitted value. Diagnostics work almost entirely on residuals.",
    "linear-regression",
    "checking-assumptions",
    "residual-plots",
  ),
  term(
    "p-value",
    "The probability of an estimate at least this extreme if the null hypothesis were true and every assumption held. Not the probability the null is true.",
    "linear-regression",
    "interpreting-results",
    "significance",
  ),
  term(
    "Confidence interval",
    "A range for the mean response at given predictor values. Narrows as the sample grows.",
    "linear-regression",
    "interpreting-results",
    "intervals",
  ),
  term(
    "Prediction interval",
    "A range for a single new observation. Always wider than a confidence interval, and it never shrinks below the irreducible noise.",
    "linear-regression",
    "interpreting-results",
    "intervals",
  ),
  term(
    "Multicollinearity",
    "Strong correlation among predictors. Does not bias predictions but makes individual coefficients unstable and hard to interpret.",
    "linear-regression",
    "interpreting-results",
    "prediction",
  ),
  term(
    "Variance inflation factor (VIF)",
    "A measure of multicollinearity for one predictor. Above 5 is worth noting, above 10 is usually serious.",
    "linear-regression",
    "interpreting-results",
    "prediction",
  ),
  term(
    "Homoskedasticity",
    "Constant error variance across the range of fitted values. Its failure invalidates standard errors, not the coefficients themselves.",
    "linear-regression",
    "checking-assumptions",
    "the-four",
  ),
  term(
    "Heteroskedasticity",
    "Error variance that changes with the fitted value — the funnel shape in a residual plot.",
    "linear-regression",
    "checking-assumptions",
    "residual-plots",
  ),
  term(
    "Cook's distance",
    "A measure of how much one observation moves the whole fit. Values above roughly 4/n deserve inspection.",
    "linear-regression",
    "checking-assumptions",
    "residual-plots",
  ),
  term(
    "Logistic regression",
    "A linear model of the log-odds of a binary outcome, so predicted probabilities are always between 0 and 1.",
    "logistic-regression",
    "why-not-linear",
    "log-odds",
  ),
  term(
    "Log-odds (logit)",
    "ln(p/(1−p)). Unbounded and symmetric about zero, which is what makes it the right scale for a linear model of probability.",
    "logistic-regression",
    "why-not-linear",
    "log-odds",
  ),
  term(
    "Odds ratio",
    "The exponentiated logistic coefficient — the multiplicative change in odds per unit of a predictor. Not the same as a relative risk unless the outcome is rare.",
    "logistic-regression",
    "fitting-and-interpreting",
    "odds-ratios",
  ),
  term(
    "Maximum likelihood",
    "Estimation by finding the parameters that make the observed data most probable. Used where least squares has no closed form.",
    "logistic-regression",
    "fitting-and-interpreting",
    "fitting",
  ),
  term(
    "Confusion matrix",
    "The 2×2 table of true and false positives and negatives. Every classification metric is a ratio of its cells.",
    "logistic-regression",
    "classification-metrics",
    "confusion-matrix",
  ),
  term(
    "Precision",
    "TP/(TP+FP) — of the cases flagged, how many were real. Optimise it when acting on a positive is expensive.",
    "logistic-regression",
    "classification-metrics",
    "precision-recall",
  ),
  term(
    "Recall (sensitivity)",
    "TP/(TP+FN) — of the real cases, how many were caught. Optimise it when missing a positive is expensive.",
    "logistic-regression",
    "classification-metrics",
    "precision-recall",
  ),
  term(
    "F1 score",
    "The harmonic mean of precision and recall. Harmonic rather than arithmetic so that being hopeless at one is not hidden by excelling at the other.",
    "logistic-regression",
    "classification-metrics",
    "f1",
  ),
  term(
    "Accuracy trap",
    "On imbalanced data, always predicting the majority class scores well. Accuracy should never be reported without its base rate.",
    "logistic-regression",
    "classification-metrics",
    "accuracy-trap",
  ),
  term(
    "ROC curve",
    "True positive rate against false positive rate across every threshold. A property of the model's ranking, independent of any one cutoff.",
    "logistic-regression",
    "thresholds-and-roc",
    "roc-curve",
  ),
  term(
    "AUC",
    "Area under the ROC curve — the probability a random positive is ranked above a random negative. 0.5 is chance, 1.0 is perfect.",
    "logistic-regression",
    "thresholds-and-roc",
    "auc",
  ),

  // Chapter 6 — trees
  term(
    "Gini impurity",
    "1 − Σpᵢ², a measure of how mixed a tree node's classes are. Zero for a pure node, 0.5 for an even two-class split.",
    "trees-and-forests",
    "how-trees-split",
    "gini-and-entropy",
  ),
  term(
    "Entropy",
    "−Σpᵢlog₂pᵢ, the average bits needed to encode a node's class. An alternative to Gini that rarely disagrees with it.",
    "trees-and-forests",
    "how-trees-split",
    "gini-and-entropy",
  ),
  term(
    "Information gain",
    "The impurity a split removes, weighted by the size of each resulting child. The quantity a tree maximises at every step.",
    "trees-and-forests",
    "how-trees-split",
    "information-gain",
  ),
  term(
    "Overfitting",
    "Learning the training data's noise as well as its signal. Diagnosed by a gap between training and held-out performance.",
    "trees-and-forests",
    "overfitting-and-pruning",
    "why-trees-overfit",
  ),
  term(
    "Cross-validation",
    "Splitting training data into k folds and validating on each in turn, so hyperparameters can be tuned without spending the test set.",
    "trees-and-forests",
    "overfitting-and-pruning",
    "cross-validation",
  ),
  term(
    "Cost-complexity pruning",
    "Growing a tree fully, then removing subtrees whose contribution does not justify their complexity. Often beats stopping early.",
    "trees-and-forests",
    "overfitting-and-pruning",
    "constraints",
  ),
  term(
    "Bagging",
    "Bootstrap aggregating: fit many models on resampled data and average them. Reduces variance without increasing bias.",
    "trees-and-forests",
    "random-forests",
    "bagging",
  ),
  term(
    "Random forest",
    "Bagged trees with an extra restriction — each split considers only a random subset of features — which decorrelates the trees and makes averaging effective.",
    "trees-and-forests",
    "random-forests",
    "feature-randomness",
  ),
  term(
    "Out-of-bag score",
    "A validation estimate from bagging: each row is scored by the ~37% of trees whose bootstrap sample excluded it.",
    "trees-and-forests",
    "random-forests",
    "bagging",
  ),
  term(
    "Permutation importance",
    "Feature importance measured by shuffling a column and observing the drop in held-out performance. Avoids the biases of impurity-based importance.",
    "trees-and-forests",
    "random-forests",
    "feature-importance",
  ),

  // Chapter 7 — time series
  term(
    "Stationarity",
    "Constant mean, constant variance, and autocovariance depending only on lag. Required because ARIMA applies one set of parameters at every time point.",
    "time-series",
    "stationarity",
    "what-it-means",
  ),
  term(
    "Differencing",
    "Replacing each value with its change from the previous one, to remove trend. Over-differencing inflates variance and injects negative autocorrelation.",
    "time-series",
    "stationarity",
    "differencing",
  ),
  term(
    "Augmented Dickey-Fuller test",
    "A test whose null hypothesis is non-stationarity, so a small p-value is the outcome you want.",
    "time-series",
    "stationarity",
    "adf-test",
  ),
  term(
    "Autocorrelation function (ACF)",
    "Correlation of a series with itself at each lag. A sharp cutoff after lag q suggests an MA(q) process.",
    "time-series",
    "acf-and-pacf",
    "autocorrelation",
  ),
  term(
    "Partial autocorrelation (PACF)",
    "Correlation at a lag after removing the effect of intervening lags. A sharp cutoff after lag p suggests an AR(p) process.",
    "time-series",
    "acf-and-pacf",
    "partial",
  ),
  term(
    "ARIMA",
    "Autoregression, integration and moving average combined. The MA component models lingering forecast errors, not a rolling average.",
    "time-series",
    "arima",
    "three-components",
  ),
  term(
    "Ljung-Box test",
    "A joint test that residual autocorrelations are zero. A large p-value is the good outcome.",
    "time-series",
    "arima",
    "diagnostics",
  ),
  term(
    "Seasonal naive",
    "Forecasting each period as the same period one season ago. A benchmark that is much harder to beat than people expect.",
    "time-series",
    "forecasts-vs-predictions",
    "the-benchmark",
  ),
  term(
    "Exponential smoothing",
    "Forecasting from a weighted average of the past with exponentially decaying weights. Holt adds a trend; Holt-Winters adds seasonality.",
    "time-series",
    "exponential-smoothing",
    "ses",
  ),
  term(
    "Damped trend",
    "Shrinking the extrapolated slope with each step ahead, so long-horizon forecasts flatten instead of growing without limit.",
    "time-series",
    "exponential-smoothing",
    "holt",
  ),

  // Chapters 8-10 — optimisation, simulation, decisions
  term(
    "Linear programming",
    "Optimising a linear objective subject to linear constraints. The formulation is harder and more important than the solve.",
    "linear-programming",
    "formulating-the-problem",
    "objective-function",
  ),
  term(
    "Binding constraint",
    "A constraint with zero slack at the optimum — the resource that ran out and stopped the objective going higher.",
    "linear-programming",
    "interpreting-and-stress-testing",
    "binding-constraints",
  ),
  term(
    "Shadow price",
    "The change in the objective from one additional unit of a resource — the most you should pay for it. Zero for non-binding constraints, and only locally valid.",
    "linear-programming",
    "interpreting-and-stress-testing",
    "shadow-prices",
  ),
  term(
    "Monte Carlo simulation",
    "Estimating a distribution by sampling a model many times. Converges at rate 1/√n, so an extra decimal digit costs 100× the compute.",
    "monte-carlo",
    "why-simulate",
    "the-idea",
  ),
  term(
    "Law of large numbers",
    "The sample mean converges to the expected value as trials accumulate. What makes simulation a legitimate substitute for algebra.",
    "monte-carlo",
    "why-simulate",
    "law-of-large-numbers",
  ),
  term(
    "Inverse transform sampling",
    "Drawing u uniformly and returning F⁻¹(u). The mechanism behind random-number intervals and behind np.random.choice.",
    "monte-carlo",
    "the-six-step-process",
    "intervals",
  ),
  term(
    "Geometric Brownian motion",
    "A price model in which log returns are independent and normal. Its Gaussian tails understate real extreme moves.",
    "monte-carlo",
    "simulating-continuous-outcomes",
    "simulating-paths",
  ),
  term(
    "Maximax",
    "Choosing the alternative with the best possible outcome. The optimist's criterion, ignoring everything but the best case.",
    "decision-analysis",
    "deciding-without-probabilities",
    "maximax",
  ),
  term(
    "Maximin",
    "Choosing the alternative whose worst outcome is best. Appropriate when the worst case is unsurvivable.",
    "decision-analysis",
    "deciding-without-probabilities",
    "maximin",
  ),
  term(
    "Minimax regret",
    "Minimising the largest shortfall against what you could have achieved had you known which state would occur.",
    "decision-analysis",
    "deciding-without-probabilities",
    "minimax-regret",
  ),
  term(
    "Expected monetary value (EMV)",
    "The probability-weighted average payoff. Correct in the long run for a risk-neutral decision maker, and misleading for one-off catastrophic decisions.",
    "decision-analysis",
    "expected-value",
    "emv",
  ),
  term(
    "EVPI",
    "Expected value of perfect information — a hard ceiling on what any study or pilot can be worth. Equals the minimum expected regret.",
    "decision-analysis",
    "expected-value",
    "evpi",
  ),
  term(
    "Rolling back",
    "Evaluating a decision tree from the leaves inward: average at chance nodes, maximise at decision nodes. Produces a policy, not a path.",
    "decision-analysis",
    "decision-trees",
    "rolling-back",
  ),

  // Chapters 11-14
  term(
    "Markov property",
    "The next state depends only on the current one, not on the path taken to reach it. Restored when it fails by enriching the state space.",
    "markov",
    "states-and-transitions",
    "the-setup",
  ),
  term(
    "Transition matrix",
    "The matrix of one-step state-change probabilities. Its rows — not columns — must each sum to 1.",
    "markov",
    "states-and-transitions",
    "transition-matrix",
  ),
  term(
    "Steady state",
    "The distribution satisfying πP = π. Individuals keep moving; the proportions stop, because flows in and out balance.",
    "markov",
    "equilibrium",
    "steady-state",
  ),
  term(
    "Absorbing state",
    "A state that is never left once entered. Chains containing one need the fundamental matrix rather than a steady state.",
    "markov",
    "absorbing-states",
    "what-absorbs",
  ),
  term(
    "Fundamental matrix",
    "N = (I − Q)⁻¹ for an absorbing chain. Nᵢⱼ is the expected visits to transient state j starting from i; row sums give time to absorption.",
    "markov",
    "absorbing-states",
    "fundamental-matrix",
  ),
  term(
    "Benford's law",
    "Leading digits of naturally occurring, multiplicatively generated numbers follow P(d) = log₁₀(1 + 1/d) — 1 appears about 30% of the time.",
    "benfords-law",
    "the-leading-digit-law",
    "the-formula",
  ),
  term(
    "Mantissa",
    "The fractional part of log₁₀ of a value. Benford conformity is exactly the statement that it is uniformly distributed.",
    "benfords-law",
    "stronger-diagnostics",
    "mantissa-stats",
  ),
  term(
    "Mean absolute deviation (MAD)",
    "Average absolute gap between observed and expected digit proportions. Independent of sample size, unlike chi-square.",
    "benfords-law",
    "testing-conformity",
    "mad",
  ),
  term(
    "Distortion factor",
    "A signed measure of whether observed values sit above or below Benford expectations — negative suggests amounts shaved downward.",
    "benfords-law",
    "stronger-diagnostics",
    "distortion-factor",
  ),
  term(
    "Work breakdown structure (WBS)",
    "A hierarchical decomposition of a project's deliverables. Governed by the 100% rule: no gaps and no overlaps.",
    "project-management",
    "work-breakdown-structure",
    "decomposing",
  ),
  term(
    "PERT estimate",
    "tₑ = (a + 4m + b)/6 from optimistic, most likely and pessimistic estimates. Exceeds the mode whenever the pessimistic tail is longer.",
    "project-management",
    "pert-estimates",
    "expected-time",
  ),
  term(
    "Critical path",
    "The longest chain of dependent activities. Its length is the project duration, and only activities on it can shorten the finish date.",
    "project-management",
    "critical-path",
    "finding-the-path",
  ),
  term(
    "Slack (float)",
    "How long an activity can be delayed without delaying the project. Belongs to a path rather than an activity, so it cannot be spent twice.",
    "project-management",
    "critical-path",
    "slack",
  ),
  term(
    "Crashing",
    "Spending money to shorten an activity. Only worth doing on critical activities, cheapest first, and with rising marginal cost.",
    "project-management",
    "risk-and-crashing",
    "crash-costs",
  ),
  term(
    "Common-cause variation",
    "The inherent, stable variation of a process. Reacting to it as though it were a signal is tampering, and it makes the process worse.",
    "quality-control",
    "control-chart-fundamentals",
    "common-vs-special",
  ),
  term(
    "Special-cause variation",
    "Variation from an identifiable external source — a worn tool, a new supplier. Findable and removable, unlike common cause.",
    "quality-control",
    "control-chart-fundamentals",
    "common-vs-special",
  ),
  term(
    "Control limits",
    "Three-sigma bounds computed from the process itself, giving about one false alarm per 370 samples. Not the same as specification limits.",
    "quality-control",
    "control-chart-fundamentals",
    "control-limits",
  ),
  term(
    "Cpk",
    "A capability index penalising both spread and off-centring. At least 1.33 is conventionally capable; below 1.0 produces out-of-spec output routinely.",
    "quality-control",
    "control-chart-fundamentals",
    "capability",
  ),
  term(
    "p-chart",
    "A control chart for the proportion of defective units, based on the binomial. Its limits move with the sample size.",
    "quality-control",
    "attribute-charts",
    "p-charts",
  ),
  term(
    "c-chart",
    "A control chart for defect counts, based on the Poisson. Distinguish a defect (one fault) from a defective (one failed unit).",
    "quality-control",
    "attribute-charts",
    "c-and-u",
  ),
  term(
    "x-bar and R chart",
    "The classical pair for measured data: one chart for the process centre, one for its spread. Always read the R chart first.",
    "quality-control",
    "variable-charts",
    "xbar-and-r",
  ),
  term(
    "Average run length (ARL)",
    "The expected number of samples before a chart signals. The honest way to compare chart designs and subgroup sizes.",
    "quality-control",
    "variable-charts",
    "subgroup-size",
  ),
  term(
    "I-MR chart",
    "Individuals and moving range, for when subgrouping is impossible. Sigma comes from the moving range so drift cannot widen its own limits.",
    "quality-control",
    "individuals-and-ewma",
    "i-mr",
  ),
  term(
    "EWMA chart",
    "A control chart on an exponentially weighted moving average. Accumulates evidence across observations, catching small sustained shifts a Shewhart chart misses.",
    "quality-control",
    "individuals-and-ewma",
    "ewma",
  ),
];

export function glossaryHref(entry: GlossaryTerm): string | null {
  if (!entry.chapter || !entry.lesson) return null;
  const base = `/chapters/${entry.chapter}/${entry.lesson}`;
  return entry.section ? `${base}#${entry.section}` : base;
}
