import type { Metadata } from "next";

import { sourceBook } from "@/lib/content";

export const metadata: Metadata = {
  title: "License and attribution",
  description:
    "How this course is licensed, what is original, and how the source book is credited.",
};

export default function LicensePage() {
  return (
    <div className="shell" style={{ maxWidth: "48rem", paddingBottom: "3rem" }}>
      <div className="chapter-hero">
        <p className="eyebrow">Legal</p>
        <h1>License and attribution.</h1>
      </div>

      <div className="page-prose">
        <h2>This course</h2>
        <p>
          The source code, lesson text, code examples and datasets in this project are original work
          released under the MIT License. You are free to use, adapt and redistribute them, with
          attribution.
        </p>

        <h2>The source book</h2>
        <p>
          The course syllabus — its chapter structure and choice of topics — follows{" "}
          <a href={sourceBook.url} rel="noreferrer noopener" target="_blank">
            <em>{sourceBook.title}</em>
          </a>{" "}
          by {sourceBook.author} ({sourceBook.publisher}, {sourceBook.year}), which is copyrighted
          commercial material and is <strong>not</strong> distributed with this project.
        </p>
        <p>Specifically:</p>
        <ul>
          <li>No text from the book is reproduced, quoted or paraphrased.</li>
          <li>No figures, tables or code listings from the book are reproduced.</li>
          <li>
            None of the book&rsquo;s datasets are redistributed. Every dataset here is synthetic and
            generated by <code>scripts/make-datasets.mjs</code>, which is included in the repository.
          </li>
          <li>
            Page citations appear throughout as pointers for further reading. Citing page numbers is
            a reference, not a reproduction.
          </li>
        </ul>
        <p>
          If you find this material useful, the book covers several of these topics in more depth
          and is worth buying.
        </p>

        <h2>Third-party software</h2>
        <p>
          The in-browser Python runtime is{" "}
          <a href="https://pyodide.org" rel="noreferrer noopener" target="_blank">
            Pyodide
          </a>{" "}
          (Mozilla Public License 2.0), loaded from a CDN at runtime. NumPy, pandas, SciPy,
          Matplotlib, scikit-learn, statsmodels, SymPy and NetworkX are all used under their
          respective open-source licenses. Typefaces are Inter, Source Serif 4 and IBM Plex Mono,
          all under the SIL Open Font License.
        </p>

        <h2>No warranty</h2>
        <p>
          This is educational material. Nothing here is professional statistical, financial, legal
          or medical advice, and the worked examples use synthetic data chosen to illustrate a
          technique rather than to describe any real situation.
        </p>
      </div>
    </div>
  );
}
