// GENERATED BY scripts/gen-lesson-components.mjs — do not edit by hand.
// Run `npm run content:map` after adding or renaming a lesson.

import type { ComponentType } from "react";

import DistributionsBinomialDistribution from "@/content/chapters/distributions/binomial-distribution.mdx";
import DistributionsConditionalProbability from "@/content/chapters/distributions/conditional-probability.mdx";
import DistributionsNormalDistribution from "@/content/chapters/distributions/normal-distribution.mdx";
import DistributionsProbabilityRules from "@/content/chapters/distributions/probability-rules.mdx";
import DistributionsUniformAndPoisson from "@/content/chapters/distributions/uniform-and-poisson.mdx";
import GroundworkHowThisCourseWorks from "@/content/chapters/groundwork/how-this-course-works.mdx";
import GroundworkThePythonToolkit from "@/content/chapters/groundwork/the-python-toolkit.mdx";
import GroundworkWhyQuantitativeThinking from "@/content/chapters/groundwork/why-quantitative-thinking.mdx";
import LinearRegressionCheckingAssumptions from "@/content/chapters/linear-regression/checking-assumptions.mdx";
import LinearRegressionFittingAModel from "@/content/chapters/linear-regression/fitting-a-model.mdx";
import LinearRegressionInterpretingResults from "@/content/chapters/linear-regression/interpreting-results.mdx";
import LinearRegressionTheLinearModel from "@/content/chapters/linear-regression/the-linear-model.mdx";
import LogisticRegressionClassificationMetrics from "@/content/chapters/logistic-regression/classification-metrics.mdx";
import LogisticRegressionFittingAndInterpreting from "@/content/chapters/logistic-regression/fitting-and-interpreting.mdx";
import LogisticRegressionThresholdsAndRoc from "@/content/chapters/logistic-regression/thresholds-and-roc.mdx";
import LogisticRegressionWhyNotLinear from "@/content/chapters/logistic-regression/why-not-linear.mdx";
import ProbabilityBasicProbability from "@/content/chapters/probability/basic-probability.mdx";
import ProbabilityCountingRules from "@/content/chapters/probability/counting-rules.mdx";
import ProbabilityPermutationsAndCombinations from "@/content/chapters/probability/permutations-and-combinations.mdx";
import ProbabilityRandomVariables from "@/content/chapters/probability/random-variables.mdx";
import TimeSeriesAcfAndPacf from "@/content/chapters/time-series/acf-and-pacf.mdx";
import TimeSeriesArima from "@/content/chapters/time-series/arima.mdx";
import TimeSeriesExponentialSmoothing from "@/content/chapters/time-series/exponential-smoothing.mdx";
import TimeSeriesForecastsVsPredictions from "@/content/chapters/time-series/forecasts-vs-predictions.mdx";
import TimeSeriesStationarity from "@/content/chapters/time-series/stationarity.mdx";
import TreesAndForestsFittingATree from "@/content/chapters/trees-and-forests/fitting-a-tree.mdx";
import TreesAndForestsHowTreesSplit from "@/content/chapters/trees-and-forests/how-trees-split.mdx";
import TreesAndForestsOverfittingAndPruning from "@/content/chapters/trees-and-forests/overfitting-and-pruning.mdx";
import TreesAndForestsRandomForests from "@/content/chapters/trees-and-forests/random-forests.mdx";

export const lessonComponents: Record<string, ComponentType> = {
  "distributions/binomial-distribution": DistributionsBinomialDistribution,
  "distributions/conditional-probability": DistributionsConditionalProbability,
  "distributions/normal-distribution": DistributionsNormalDistribution,
  "distributions/probability-rules": DistributionsProbabilityRules,
  "distributions/uniform-and-poisson": DistributionsUniformAndPoisson,
  "groundwork/how-this-course-works": GroundworkHowThisCourseWorks,
  "groundwork/the-python-toolkit": GroundworkThePythonToolkit,
  "groundwork/why-quantitative-thinking": GroundworkWhyQuantitativeThinking,
  "linear-regression/checking-assumptions": LinearRegressionCheckingAssumptions,
  "linear-regression/fitting-a-model": LinearRegressionFittingAModel,
  "linear-regression/interpreting-results": LinearRegressionInterpretingResults,
  "linear-regression/the-linear-model": LinearRegressionTheLinearModel,
  "logistic-regression/classification-metrics": LogisticRegressionClassificationMetrics,
  "logistic-regression/fitting-and-interpreting": LogisticRegressionFittingAndInterpreting,
  "logistic-regression/thresholds-and-roc": LogisticRegressionThresholdsAndRoc,
  "logistic-regression/why-not-linear": LogisticRegressionWhyNotLinear,
  "probability/basic-probability": ProbabilityBasicProbability,
  "probability/counting-rules": ProbabilityCountingRules,
  "probability/permutations-and-combinations": ProbabilityPermutationsAndCombinations,
  "probability/random-variables": ProbabilityRandomVariables,
  "time-series/acf-and-pacf": TimeSeriesAcfAndPacf,
  "time-series/arima": TimeSeriesArima,
  "time-series/exponential-smoothing": TimeSeriesExponentialSmoothing,
  "time-series/forecasts-vs-predictions": TimeSeriesForecastsVsPredictions,
  "time-series/stationarity": TimeSeriesStationarity,
  "trees-and-forests/fitting-a-tree": TreesAndForestsFittingATree,
  "trees-and-forests/how-trees-split": TreesAndForestsHowTreesSplit,
  "trees-and-forests/overfitting-and-pruning": TreesAndForestsOverfittingAndPruning,
  "trees-and-forests/random-forests": TreesAndForestsRandomForests,
};
